[package]
name = "the_nightmarish_forest"
version = "0.0.1"
edition = "2021"

[dependencies]
bevy = { version = "0.15.3", features = ["dynamic_linking"] }
educe = "0.6.0"
autodefault = "2.0.0"
bevy-inspector-egui = "0.30"
bevy-add-events-macro = "0.1.0"
avian3d = "0.2.1"

[profile.dev.package."*"]
opt-level = 3

